use thiserror::Error;
use wednesday_model::error::{DataError, SocketError};

/// All Errors generated by the wednesday-core::data module.
#[derive(Error, Debug)]
pub enum DataFeederError {
    #[error("Invalid builder attributes provided")]
    BuilderAttributesInvalid,

    #[error("Failed to build struct due to missing attributes: {0}")]
    BuilderIncomplete(&'static str),

    #[error("Socket: {0}")]
    Socket(#[from] SocketError),

    #[error("Barter-Data: {0}")]
    Data(#[from] DataError),
}